window.BLOG_META = {
  "categories": [
    "Books",
    "Career",
    "Chat",
    "Culture",
    "Finance",
    "Food",
    "Health",
    "Healthy",
    "Life Story",
    "Lifestyle",
    "Music",
    "Personal Growth",
    "Philosophy",
    "Productivity",
    "Psychology",
    "Review",
    "Story",
    "Sukee's Pick",
    "Technology",
    "Things To Do",
    "Thoughts",
    "Travel",
    "Zen"
  ],
  "tags": [
    "12-Week Project",
    "2024",
    "Acceptance",
    "Accountability",
    "Activities",
    "Adaptation",
    "Afternoon Tea",
    "Agency",
    "AI",
    "Andrea Bocelli",
    "Animals",
    "Animation",
    "Anxiety",
    "Apple Notes",
    "Attention",
    "August",
    "Austin",
    "Authenticity",
    "Autonomy",
    "Awareness",
    "Biology",
    "Blogging",
    "Books",
    "Boundaries",
    "Breast Cancer",
    "Brunch",
    "Bucket List",
    "Budgeting",
    "Bullet Journal",
    "Business",
    "Butterfly Effect",
    "Calendar",
    "Cape Verde",
    "Career",
    "Cause and Effect",
    "Cello",
    "Change",
    "ChatGPT",
    "Chemicals",
    "Child Development",
    "Children",
    "Chinese",
    "Choice",
    "CIA",
    "Circle of Competence",
    "Classical",
    "Coffee",
    "Comfort",
    "Communication",
    "Community",
    "Competition",
    "Confidence",
    "Conformity",
    "Connection",
    "Consulting",
    "Consumerism",
    "Control",
    "Conversation",
    "Cooking",
    "Country Music",
    "Courage",
    "Creativity",
    "Critical Thinking",
    "Culture",
    "Current Events",
    "Daily Routine",
    "Dale Carnegie",
    "Dance",
    "Data",
    "Data Engineering",
    "Decision Making",
    "Decluttering",
    "Deja Vu",
    "Dental Health",
    "Depth",
    "Design",
    "Diet",
    "Digital Detox",
    "Digital Minimalism",
    "Dining",
    "Direction",
    "Disneyland",
    "Dr. Nicole Lepera",
    "Dreams",
    "Dunbar",
    "Earth Day",
    "Eclipse",
    "Economics",
    "Education",
    "Efficiency",
    "Electric Vehicle",
    "Emergency Prep",
    "Emotions",
    "Energy Efficiency",
    "Environment",
    "Ethics",
    "Evernote",
    "Evolution",
    "Excel",
    "Excellence",
    "Execution",
    "Exercise",
    "Expectations",
    "Exploration",
    "Eye Care",
    "Faith",
    "Family",
    "Festival",
    "Finance",
    "FIRE",
    "Flamenco",
    "Florida",
    "Flowers",
    "Focus",
    "Food",
    "Food Safety",
    "Forensics",
    "Frameworks",
    "Fraud",
    "Freedom",
    "French Bakery",
    "Friendship",
    "Frugality",
    "Fun",
    "Fun Facts",
    "Gardening",
    "Gautier Capucon",
    "Generosity",
    "Goal Setting",
    "Graduation",
    "Gratitude",
    "Group Behavior",
    "Growth",
    "Guitar",
    "Habits",
    "Hauser",
    "Hawaii",
    "Healing",
    "Health",
    "Health Insurance",
    "History",
    "Holiday",
    "Holistic Thinking",
    "Home",
    "Home Improvement",
    "Horror",
    "Hospitality",
    "HSA",
    "Human Nature",
    "Humility",
    "Humor",
    "Ice Cream",
    "Iced Tea",
    "Identity",
    "IKIGAI",
    "Imperfection",
    "Income",
    "India",
    "Individuality",
    "Inflammation",
    "Influence",
    "Injury",
    "Innovation",
    "Insight",
    "Inspiration",
    "Interview",
    "Introversion",
    "Investing",
    "Japan",
    "Jealousy",
    "Job Search",
    "John Doerr",
    "Journaling",
    "Keynote",
    "Kindness",
    "Knowledge Management",
    "Korean Food",
    "La Madeleine",
    "Language",
    "Law",
    "Law of Attraction",
    "Leadership",
    "Learned Helplessness",
    "Learning",
    "Legal",
    "Lemmings",
    "Lessons",
    "Letting Go",
    "Life Decisions",
    "Life Design",
    "Life Lessons",
    "Life Philosophy",
    "Life Planning",
    "Life Skills",
    "Life System",
    "Lifestyle",
    "Literature",
    "Locusts",
    "Love",
    "Luke Combs",
    "Lyrics",
    "MacBook",
    "Management",
    "Manifestation",
    "Mantra",
    "Maslow",
    "MBA",
    "Medicare",
    "Meditation",
    "Memory",
    "Mental Health",
    "Metaphor",
    "Michelin",
    "Miley Cyrus",
    "Military",
    "Mindfulness",
    "Mindset",
    "Minimalism",
    "MKUltra",
    "Money",
    "Monthly Review",
    "Morning Routine",
    "Motherhood",
    "Motivation",
    "Movies",
    "Museums",
    "Music",
    "Myth",
    "Nature",
    "Negotiation",
    "New York",
    "News",
    "Note-taking",
    "Notion",
    "Nutrition",
    "Observation",
    "OKR",
    "Opera",
    "Organization",
    "Outdoors",
    "Parenting",
    "Passion Fruit",
    "Patience",
    "Peace",
    "Personal Finance",
    "Personal Growth",
    "Perspective",
    "Philosophy",
    "Piano",
    "Pickleball",
    "Poetry",
    "Pop Music",
    "Portfolio",
    "Positivity",
    "Practicality",
    "Presence",
    "Prevention",
    "Priorities",
    "Problem Solving",
    "Procrastination",
    "Productivity",
    "Progress",
    "Project Management",
    "Psychology",
    "Purpose",
    "Quality of Life",
    "Questions",
    "Reading",
    "Real Estate",
    "Recipe",
    "Reflection",
    "Regret",
    "Relationships",
    "Relaxation",
    "Religion",
    "Research",
    "Resilience",
    "Restaurants",
    "Retirement",
    "Risk Management",
    "Running",
    "Safety",
    "Sahil Bloom",
    "Sales",
    "Samba",
    "Science",
    "Security",
    "Self-acceptance",
    "Self-Actualization",
    "Self-Awareness",
    "Self-Care",
    "Self-Discovery",
    "Self-esteem",
    "Self-Healing",
    "Self-Improvement",
    "Shortcuts",
    "Simplicity",
    "Skepticism",
    "Skills",
    "Skin",
    "Sleep",
    "Social",
    "Social Circles",
    "Social Intelligence",
    "Social Media",
    "Social Science",
    "Society",
    "Solitude",
    "Soundscape",
    "Spirituality",
    "Sports",
    "Sting",
    "Stoicism",
    "Story",
    "Storytelling",
    "Strategy",
    "Stress",
    "Study",
    "Subconscious",
    "Success",
    "Sukee's Pick",
    "Sustainability",
    "Systems Thinking",
    "Task Management",
    "Tea",
    "Tea Time",
    "Technology",
    "Television",
    "Texas",
    "The Shawshank Redemption",
    "Thinking",
    "Time",
    "Timeless",
    "Tips",
    "To-Do List",
    "Tools",
    "Traditions",
    "Travel",
    "Trust",
    "Turnaround",
    "Values",
    "Vegan",
    "Visual Literacy",
    "Visualization",
    "Walking",
    "Warmth",
    "Water",
    "Water Quality",
    "Wealth",
    "Wealth Building",
    "Weight Loss",
    "Wellness",
    "Wheel of Life",
    "Wine",
    "Wisdom",
    "Work",
    "Workplace",
    "Worship",
    "Writing",
    "Yo-Yo Ma",
    "YouTube",
    "Zen"
  ]
};
